from newsable.news.News import News
from newsable.news.Bernama import Bernama
from newsable.news.BorneoPost import BorneoPost
from newsable.news.FreeMalaysiaToday import FreeMalaysiaToday
from newsable.news.IpohEcho import IpohEcho
from newsable.news.MalayMail import MalayMail
from newsable.news.MalaysiaChronicle import MalaysiaChronicle
from newsable.news.MalaysiaKini import MalaysiaKini
from newsable.news.MySinchew import MySinchew
from newsable.news.NewStraitsTimes import NewStraitsTimes
from newsable.news.Selangorku import Selangorku
from newsable.news.SelangorTimes import SelangorTimes
from newsable.news.TheMalaysianInsider import TheMalaysianInsider
from newsable.news.TheStar import TheStar
from newsable.news.TheSunDaily import TheSunDaily